packages/zipkin-instrumentation-express/README.md

Adding .expressMiddleware to require() prevents the following error:
app.use(zipkinMiddleware({
^
TypeError: zipkinMiddleware is not a function

update README.md to working example

---

README.md
packages/zipkin-instrumentation-restify/README.md
packages/zipkin-instrumentation-restify/index.js
packages/zipkin-instrumentation-restify/package.json
packages/zipkin-instrumentation-restify/src/restifyMiddleware.js
packages/zipkin-instrumentation-restify/test/.eslintrc
packages/zipkin-instrumentation-restify/test/integrationTest.js

I created a port of the express middleware that works with [Restify](http://restify.com/). There's just a few APIs that vary between Restify and Express, mainly around what methods are available on the request object. I updated the integration tests to match and they currently pass. The README contains example usage as well. 
Anyway, I'm open to any changes. I could also publish this myself but thought it might belong with the other instrumentations you have available. Let me know! Thanks!

Add Restify instrumentation package

---

packages/zipkin-transport-kafka/README.md

Adding destructuring braces to `KafkaLogger` import

Fix kafka logger example in README

---

lerna.json
packages/zipkin-transport-http/README.md
packages/zipkin-transport-http/index.js
packages/zipkin-transport-http/package.json
packages/zipkin-transport-http/src/HttpLogger.js
packages/zipkin-transport-http/test/.eslintrc
packages/zipkin-transport-http/test/integrationTest.js
packages/zipkin/src/internalRepresentations.js
packages/zipkin/test/internalRepresentations.test.js

Fixes #15. I modeled most of this after the scribe and kafka loggers. Basically, there is just an internal queue that gets checked every second for new spans. If there are spans, it batches them up in a single JSON post (an array) and sends them to a configurable HTTP endpoint.
Let me know if you'd like any changes made! I've tested this on a Restify-based service and I also added unit / integration tests.

Adding HTTP transport module

---

packages/zipkin/src/batch-recorder.js

I noticed my node process wasn't exiting when there was nothing else running, and discovered it was the timer in BatchRecorder that was still running. Anyway, made the same fix that @sveisvei suggested to BatchRecorder to solve the problem.

unref the timer in BatchRecorder

---

packages/zipkin-transport-http/README.md

Rename httpRecorder to recorder because Tracer is specifically looking for a parameter named "recorder" or it throws an error like:
Error: Tracer: Missing required argument recorder.
at requiredArg (/Users/Kevin/myservice1/node_modules/zipkin/src/tracer/index.js:11:9)
at new Tracer (/Users/Kevin/myservice1/node_modules/zipkin/src/tracer/index.js:17:16)
at Object.<anonymous> (/Users/Kevin/myservice1/app.js:17:16)

fix "Missing required argument recorder" error

---

packages/zipkin/src/gen-nodejs/zipkinCore_types.js
packages/zipkin/src/internalRepresentations.js
packages/zipkin/src/tracer/index.js
packages/zipkin/src/tracer/record.js
packages/zipkin/src/zipkinCore.thrift

Annotation.duration is an obsolete field and was removed last year from
the thrift.

Removes obsolete Annotation.duration

---

packages/zipkin/src/time.js
packages/zipkin/test/batch-recorder.test.js
packages/zipkin/test/trace.test.js

Before, the microsecond portion of the timestamp was filled with the
milliseconds value. This is mostly harmless, but incorrect. It is
better to truncate to millis until we record microsecond granularity.
See #3

Fixes bug where millis were used as micros

---

packages/zipkin-instrumentation-express/src/expressMiddleware.js
packages/zipkin-instrumentation-express/test/integrationTest.js

This fixes the reporting of the path when the path includes a query string. Previously, a URL like `http://localhost:8180/api/bonjour?_=1473407259102` would be reported on `http.url` as `http://localhost:8180/api/bonjour%3F_=1473407259102`. With this change, the `http.url` is now reported as `http://localhost:8180/api/bonjour?_=1473407259102`.
Before: https://snag.gy/xr4Zow.jpg
After: https://snag.gy/z4VB5O.jpg
References: https://nodejs.org/api/url.html#url_url_format_urlobject

Fixed the reported path with querystring.

---

packages/zipkin-transport-kafka/README.md

There are two required keys when creating a Tracer, `ctxImpl` and `recorder`, the latter key was missing in the example. 
cc @rodrwan

Fix javascript example in zipkin-transport-kafka package

---

packages/zipkin-instrumentation-express/test/integrationTest.js
packages/zipkin-instrumentation-restify/test/integrationTest.js
packages/zipkin/src/tracer/TraceId.js
packages/zipkin/test/TraceId.test.js

The first step of transitioning to 128bit `X-B3-TraceId` is tolerantly reading 32 character long ids by throwing away the high bits (any characters left of 16 characters). This allows the tracing system to more flexibly introduce 128bit trace id support in the future.
Ex. when `X-B3-TraceId: 463ac35c9f6413ad48485a3953bb6124` is received, parse the lower 64 bits (right most 16 characters ex48485a3953bb6124) as the trace id.
See https://github.com/openzipkin/b3-propagation/issues/6

Tolerate reads of 128 bit X-B3-TraceId

---

README.md

This makes links from the top-level README to each package. The reordering is to put the instrumentations in alphabetical order which makes them easier to skim read.
Links have also been added for the transport packages.

README polish

---

packages/zipkin-transport-kafka/package.json

closes #24.
There should be only fixes here, so a minor jump is fine.
https://github.com/SOHU-Co/kafka-node/blob/master/CHANGELOG.md

upgrade kafka-node

---

README.md
lerna.json
package.json
packages/zipkin/src/batch-recorder.js
packages/zipkin/src/internalRepresentations.js
packages/zipkin/src/time.js
packages/zipkin/src/tracer/index.js
packages/zipkin/test/batch-recorder.test.js
packages/zipkin/test/explicit-context.test.js
packages/zipkin/test/internalRepresentations.test.js
packages/zipkin/test/trace.test.js

This uses the same approach as Brave does, except using process.hrtime
instead of Java's `System.nanoTime`. Here's the approach in summary:
When creating a tracer or a span, save off the relative time and make
timestamps based on an high-precision offset from there.
In browsers, microsecond precision requires installing a shim like this:
```
// use higher-precision time than milliseconds
process.hrtime = require('browser-process-hrtime');
```
Here's an actual trace that uses this code, starting from the browser and continuing to the server:
See https://nodejs.org/api/process.html#process_process_hrtime_time
See https://github.com/kumavis/browser-process-hrtime
Fixes #29
Fixes #3

Supports microsecond precision by employing process.hrtime

---

packages/zipkin-instrumentation-cujojs-rest/README.md
packages/zipkin-instrumentation-cujojs-rest/src/restInterceptor.js
packages/zipkin-instrumentation-cujojs-rest/test/integrationTest.js
packages/zipkin-instrumentation-fetch/README.md
packages/zipkin-instrumentation-fetch/src/wrapFetch.js
packages/zipkin-instrumentation-fetch/test/integrationTest.js
packages/zipkin-instrumentation-memcached/src/zipkinClient.js
packages/zipkin-instrumentation-memcached/test/integrationTest.js
packages/zipkin-instrumentation-redis/src/zipkinClient.js
packages/zipkin-instrumentation-redis/test/integrationTest.js
packages/zipkin/src/annotation.js
packages/zipkin/src/batch-recorder.js
packages/zipkin/src/gen-nodejs/zipkinCore_types.js
packages/zipkin/src/internalRepresentations.js
packages/zipkin/src/zipkinCore.thrift
packages/zipkin/test/batch-recorder.test.js
packages/zipkin/test/internalRepresentations.test.js

The ServerAddr("sa") annotation is used to indicate the server. This is
used for uninstrumented clients, such as redis. When used properly, the
Zipkin dependencies graph will show those who call into such services.
This adds an option `remoteServiceName` which hints the name of the
peer. Where possible, other endpoint information such as host and port
are added.
Fixes #52

Adds remoteServiceName which maps to the ServerAddr binary annotation

---

README.md

Looking at the development activity and usage statistics, I believe we can consider zipkin-js somewhat stable by now.

No work in progress?

---

packages/zipkin-transport-kafka/package.json

Breaking change is dropped support for node < 4, which is no problem here.
https://github.com/SOHU-Co/kafka-node/blob/master/CHANGELOG.md
/cc @sveisvei @eirslett

Upgrade to kafka-node@1.0.0

---

packages/zipkin-instrumentation-express/test/integrationTest.js
packages/zipkin-instrumentation-hapi/test/integrationTest.js
packages/zipkin-instrumentation-restify/test/integrationTest.js
packages/zipkin/README.md
packages/zipkin/src/gen-nodejs/zipkinCore_types.js
packages/zipkin/src/internalRepresentations.js
packages/zipkin/src/tracer/TraceId.js
packages/zipkin/src/tracer/index.js
packages/zipkin/src/tracer/randomTraceId.js
packages/zipkin/src/zipkinCore.thrift
packages/zipkin/test/TraceId.test.js
packages/zipkin/test/internalRepresentations.test.js
packages/zipkin/test/randomTraceId.test.js
packages/zipkin/test/trace.test.js

Before, we threw out high bits when receiving 128-bit trace IDs. This
retains and reports them to Zipkin.
When a Tracer is initialized with `traceId128Bit: true`, the trace IDs
will be 128-bit (32 characters) as opposed to 64-bit. In either case,
span IDs within a trace are 64-bit (16 characters).
To simplify things, this does away with variable length ID generation
in favor of the de-facto fixed length. It is unlikely that random
numbers would have a lot of leading zeros to optimize out anyway.

Propagates, reports and optionally generates 128-bit trace IDs

---

packages/zipkin-transport-scribe/test/gen-nodejs/scribe.js
packages/zipkin-transport-scribe/test/gen-nodejs/scribeServer_types.js
packages/zipkin/src/gen-nodejs/zipkinCore_types.js

Because of [a bug in the thrift compiler](https://issues.apache.org/jira/browse/THRIFT-1840), it generates javascript that leaks objects into the global context. This patch simply edits the generated thrift files to fix that ( hopefully all of them ).

Modify generated thrift files to fix global object leak

---

packages/zipkin-instrumentation-hapi/src/hapiMiddleware.js
packages/zipkin-instrumentation-hapi/test/integrationTest.js

In hapi, you can respond with an error, which will be wrapped by [Boom](https://github.com/hapijs/boom). In this case, `response.statusCode` is undefined, since `response` is an instance of a Boom error.
Currently, it crashes when going to a route that produces an error (such as a 404) due to calling `toString()` on undefined. This PR fixes this by checking if the response is a Boom instance and retrieving the status code from that.

Fix crash when hapi responds with error

---

packages/zipkin-instrumentation-express/src/wrapExpressHttpProxy.js

Node url changed its formatting between v6 and 7. See https://github.com/nodejs/node/issues/11103
This will maintain backwards compatibility with 6 and 7. @rexxars

Slashes: true to resolve url format breaking changes between node v6/7

---

packages/zipkin-instrumentation-express/src/wrapExpressHttpProxy.js
packages/zipkin-instrumentation-express/test/wrapExpressHttpProxyIntegrationTest.js

Got ahead of myself and missed the base test case. Added.
This was failing when `wrappedOptions.decorateRequest` and/or `wrappedOptions.intercept` were not defined.

Add check if decorateRequest/intercept are not defined.

---

packages/zipkin-instrumentation-request/src/wrapRequest.js
packages/zipkin-instrumentation-request/test/integrationTest.js

White space aside, the biggest change is to use `.on('response', ...)` instead of wrapping the optional callback. Some libraries (like `express-request-proxy` which use `request` internally) do not always include a callback. There is the option to listen for a `response` event. This event is always emitted by `request` when a response is returned so I think it's a better approach then the original `wrappedCallback`.

Use events instead of optional callback

---

packages/zipkin-instrumentation-fetch/src/wrapFetch.js
packages/zipkin-instrumentation-fetch/test/integrationTest.js

This will allow the errors to be shown in the UI as well as follows the standard for error recording.

Rename ‘request.error’ to ‘error’

---

packages/zipkin-transport-http/src/HttpLogger.js

The problem: if some messages are added to queue while pushing to zipkin, they will be lost.

fix problem with skipping some messages in HttpLogger.js

---

packages/zipkin/test/batch-recorder.test.js

Default span names are good choices as they are bounded. However, users
may want to change these to other bounded choices (ex names that don't
include variables). This shows how to accomplish this.
Note: it is quite common for custom code to get naming wrong, by using
high cardinality names such as specific http paths. This is one reason
why defaults are limited, as tags/binary annotations can be used to add
more specific lookup criteria without degrading the UI.
See #96
See https://github.com/openzipkin/openzipkin.github.io/issues/70#issuecomment-290880552

Adds tests that shows how to override the span name

---

packages/zipkin-instrumentation-redis/src/zipkinClient.js
packages/zipkin-instrumentation-redis/test/integrationTest.js

In #116 I made an unfortunate error and passed an array to recordBinary.. This will create an erroneous trace, which cannot be sent to zipkin.

Fix: Binary annotation cannot be array (must be string)

---

packages/zipkin-encoder-thrift/src/index.js
packages/zipkin-encoder-thrift/test/index.test.js
packages/zipkin-transport-http/test/integrationTest.js
packages/zipkin/src/batch-recorder.js
packages/zipkin/src/jsonEncoder.js
packages/zipkin/src/model.js
packages/zipkin/test/batch-recorder.test.js
packages/zipkin/test/jsonEncoder.JSON_V1.test.js
packages/zipkin/test/jsonEncoder.JSON_V2.test.js
packages/zipkin/test/model.test.js

Integrating react native, I noticed we weren't recording spans against
the default service name set by instrumentation (always 'unknown').
This also fixes some other glitches noticed when looking carefully at
the data as well the lint problem ignored formerly.

Cleans up glitches, notably re-enabling 'unknown' service names

---

packages/zipkin-transport-http/README.md
packages/zipkin-transport-http/src/HttpLogger.js
packages/zipkin-transport-http/test/integrationTest.js

This is needed because our Zipkin server is protected by tokens that must be sent as HTTP headers.

Add support for setting custom HTTP headers in HTTP transport

---

packages/zipkin/src/tracer/index.js
packages/zipkin/test/trace.test.js

Before, we were unconditionally recording annotations and tags.
Fixes #152

Honors sampling flag by not recording data when false

---

packages/zipkin-instrumentation-express/index.d.ts
packages/zipkin-instrumentation-express/package.json
packages/zipkin-instrumentation-request/index.d.ts
packages/zipkin-instrumentation-request/package.json
packages/zipkin/index.d.ts

Fix `packages/zipkin/index.d.ts`, which had some duplicate declarations because pawel’s commit dc62adeb3dc47eafff02abedff50356ba5f8278f was rebased on top of my commits 95abee9f43165cd30e9066567df260e66a8e1ee1, e387cfa9ea4c7c14b5d1650c062ed253818e54b0, fedc9bc2ed10dad9de429df5b5cef84d89324a70.
Add typescript declarations for zipkin-instrumentation-express and zipkin-instrumentation-request

Typescript declarations for zipkin-instrumentation-express and zipkin-instrumentation-request

---

packages/zipkin/index.d.ts

Fix the type of ipv4 for Endpoint constructor
Add fields of the Annotation subclasses

TypeScript type fix, and add fields

---

packages/zipkin/src/instrumentation/httpServer.js
packages/zipkin/test/httpServerInstrumentation.test.js

https://github.com/openzipkin/zipkin-js/issues/171

Tolerating boolean literals sent by libraries like zipkin-go-opentracing in b3

---

packages/zipkin-transport-http/index.d.ts
packages/zipkin-transport-http/src/HttpLogger.js

had some trouble figuring out how to test this.. any suggestions? I started down the path of something like:
```javascript
it('should abort the request if response exceeds timeout', function(done) {
// ..
app.post('/api/v1/spans', (req, res) => {
setTimeout(() => { res.status(202).json({}); }, 61000);
});
// ...
this.server = app.listen(0, () => {
// ..
const httpLogger = new HttpLogger({
endpoint: `http://localhost:${this.port}/api/v1/spans`,
headers: {Authorization: 'Token'},
jsonEncoder: JSON_V2,
timeout: 2000,
});
// .. 
});
});
```
But I'm not sure how to get a reference to the promise returned by fetch.. any advice would be welcome!
closes #163

add support for optional fetch timeout

---

packages/zipkin-instrumentation-memcached/src/zipkinClient.js
packages/zipkin-instrumentation-postgres/src/zipkinClient.js
packages/zipkin-instrumentation-redis/src/zipkinClient.js
packages/zipkin/index.d.ts
packages/zipkin/src/tracer/index.js
packages/zipkin/test/trace.test.js

This adds letId which is a shortcut to combining tracer.scoped with
setId. It pays for the additional code by removing an unused function:
tracer.letChildId

Trades unused letChildId for letId

---

packages/zipkin-transport-kafka/src/KafkaLogger.js

Remove listeners when producer sends or fails to send, to avoid memory leaks when trace has a lot of spans.

Fix memory leak for not closing kafka producer listeners

---

packages/zipkin-instrumentation-postgres/README.md

Fixes typo in "instrumentation" in README file.

Corrects spelling in zipkin-instrumentation-postgres

---

packages/zipkin/index.d.ts

Instrumentation.HttpServer.recordRequest returns a TraceId object, not a string.
Instrumentation.HttpClient/HttpClient.recordResponse takes a TraceId object, not a string.

Fix return type of HttpServer.recordRequest

---

packages/zipkin-transport-kafka/src/KafkaLogger.js

Removed promise in KafkaLogger.js and provide access to the producer within logSpan. onError is always bound to the producer (not sure why removeAllListeners is ever called), and can be defined in the constructor.

kafkaLogger unhandled error in promise fix

---

packages/zipkin/src/annotation.js
packages/zipkin/src/batch-recorder.js
packages/zipkin/src/jsonEncoder.js
packages/zipkin/test/batch-recorder.test.js

Hi,
I added the `MessageSend`, `MessageRecv`, `WireSend`, `WireRecv` annotation type to support message tracing. Referenced the discussion in #215 
One thing I'm still not sure is how to handle `WireSend` and `WireRecv` spans in `batch-recorder.js`, can someone give me some help on this part? I'd like very much to finish this feature and get the PR merged.
Thanks!

added message tracing annotations

---

packages/zipkin-instrumentation-restify/src/restifyMiddleware.js
packages/zipkin-instrumentation-restify/test/integrationTest.js

Added functionality to pass an error to the [httpServer](https://github.com/openzipkin/zipkin-js/blob/6a12a1d3bb0567e7e3e3e69a69a1c4bffdeb0351/packages/zipkin/src/instrumentation/httpServer.js#L86) recordResponse function on status codes >=400 to indicate them as an error.

Addresses issue #220

---

packages/zipkin-transport-http/index.d.ts

The HttpLogger accepts an option of Http headers to add to the outgoing request. This adds support for that option to the accompanying type definition file.

Adds headers option to HttpLogger types

---

.gitignore
packages/zipkin-instrumentation-express/test/wrapExpressHttpProxyIntegrationTest.js
packages/zipkin-instrumentation-hapi/test/integrationTest.js
packages/zipkin-instrumentation-restify/test/integrationTest.js
packages/zipkin/src/instrumentation/httpServer.js
packages/zipkin/test/httpServerInstrumentation.test.js

This PR removes the `'X-B3-Flags'` from the binary annotations (aka tags): actual removal is in https://github.com/openzipkin/zipkin-js/compare/removes_unnecessary_debug_tag?expand=1#diff-13acaf8526b6f17f74c05c209a6c833c and the rest are tests.
Ping @adriancole @eirslett

[#57] Removes http header binary annotation in spans.

---

packages/zipkin-instrumentation-cujojs-rest/test/integrationTest.js
packages/zipkin-instrumentation-express/src/wrapExpressHttpProxy.js
packages/zipkin-instrumentation-express/test/expressMiddlewareIntegrationTest.js
packages/zipkin-instrumentation-express/test/wrapExpressHttpProxyIntegrationTest.js
packages/zipkin-instrumentation-fetch/test/integrationTest.js
packages/zipkin-instrumentation-hapi/test/integrationTest.js
packages/zipkin-instrumentation-request/test/integrationTest.js
packages/zipkin-instrumentation-restify/test/integrationTest.js
packages/zipkin/src/index.js
packages/zipkin/src/instrumentation/httpClient.js
packages/zipkin/src/instrumentation/httpServer.js
packages/zipkin/src/parseUrl.js
packages/zipkin/test/httpClientInstrumentation.test.js
packages/zipkin/test/httpServerInstrumentation.test.js

At the moment, Zipkin JS is including `http.url` as annotation including all query strings. This has some privacy issues (e.g. passing e-mails or tokens in query parameters) so most zipkin instrumentations include the `http.path` instead.
Ping @jcchavezs @adriancole

[Issue #217] Remove http.url annotation in favor of http.path and http.host

---

packages/zipkin/index.d.ts

I adapted the Typescript definition file to match the implementation. I didn't change the implementation because I don't know what it's the intention of the developers. `BatchRecorder` receives a `Logger` type.
https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin/src/console-recorder.js#L8
vs
https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin/src/batch-recorder.js#L59

fix: kipkin ConsoleRecorder constructor does not match ts type

---

packages/zipkin/index.d.ts
packages/zipkin/src/instrumentation/httpServer.js
packages/zipkin/src/option.js
packages/zipkin/src/tracer/TraceId.js
packages/zipkin/src/tracer/index.js
packages/zipkin/test/httpServerInstrumentation.test.js

This PR fixes a bug in the sampling flags extraction as we were providing a `optional` value in https://github.com/openzipkin/zipkin-js/pull/247/files#diff-5afae8abcf08e9bdf241cbb7eed71aaaR8
Also it fixes a problem because the new context was created on top of the any existing one by using the https://github.com/openzipkin/zipkin-js/pull/247/files#diff-aa30be809cfe81ece1c873af6639ef3cR70

Fixes sampling flags extraction.

---

packages/zipkin-transport-http/src/HttpLogger.js
packages/zipkin-transport-http/test/integrationTest.js

We have mimicked the Zipkin API but don't use 202s since they are not appropriate in our case.

Relax response code expectation to allow 200s

---

package.json

While publishing a new release for `zipkin-js` we had some issues with deprecations, notably from `npm prepublish`. Upgrading lerna solves those issues as it stop using `prepublish` and uses `prepare` instead.
Ping @adriancole @eirslett

Upgrades lerna to avoid npm deprecations due to prepublish.

---

packages/zipkin-transport-http/src/HttpLogger.js
packages/zipkin/package.json
packages/zipkin/src/InetAddress.js
packages/zipkin/src/network.js

Since require.call it's making webpack give some warnings, I'm removing it and using only require. The change was made on "INetAddress" on zipkin package and on "HttpLogger" on zipkin-transport-http package.
The tests continue passing as it should.
Closes #195

Removing require.call

---

packages/zipkin/index.d.ts

I recently [ported the zipkin TS defs to Flow](https://github.com/flow-typed/flow-typed/pull/2953).  In the process, I found a couple types that seemed incorrect:
* Endpoint isEmpty's implementation returns a boolean, but the TS def was returning void.
* ~~The usual type of flatMap (i.e. monadic bind) is `(a -> Option b) -> Option a -> Option b`.  The TS types seemed to be identical to `map`, but the current Some flatMap implementation _seems_ to be similar to map + monadic join (using getOrElse as join).  I realize there may be a reason (historical?) for the TS type, but this change seemed right and I included it in this PR.~~ We decided to handle this in another PR ([see comment](https://github.com/openzipkin/zipkin-js/pull/280#issuecomment-439188846))
I included both of these changes …

Update Endpoint isEmpty

---

package.json
packages/zipkin/test-types/TraceId.test.ts
packages/zipkin/test-types/annotation.test.ts
packages/zipkin/test-types/context.test.ts
packages/zipkin/test-types/inetAddress.test.ts
packages/zipkin/test-types/instrumentation.test.ts
packages/zipkin/test-types/jsonEncoder.test.ts
packages/zipkin/test-types/model.test.ts
packages/zipkin/test-types/randomTraceId.test.ts
packages/zipkin/test-types/recorder.test.ts
packages/zipkin/test-types/request.test.ts
packages/zipkin/test-types/sampler.test.ts
packages/zipkin/test-types/trace.test.ts

Issue: `lint:ts` command doesn't lint all of the sub-folders.
Fix: Change the `lint:ts` command to match all sub-folders.
The discussion in #286 where there were some missing semicolons in the PR.

Change the lint:ts command to match all sub-folders.

---

.eslintignore
.gitignore
packages/zipkin-transport-http/README.md
packages/zipkin-transport-http/index.d.ts
packages/zipkin-transport-http/src/HttpLogger.js
packages/zipkin-transport-http/test/integrationTest.js
packages/zipkin-transport-kafka/README.md
packages/zipkin-transport-kafka/index.d.ts
packages/zipkin-transport-kafka/src/KafkaLogger.js
packages/zipkin-transport-scribe/README.md
packages/zipkin-transport-scribe/index.d.ts
packages/zipkin-transport-scribe/src/ScribeLogger.js
packages/zipkin/index.d.ts
packages/zipkin/src/tracer/index.js

Enables the application to pass a logging module as argument to be used instead of hardcoding to `console`, which will just print a string.
This is specially important for the transports, as production applications will likely use logging aggregation which will expect a specific format.
I was on the fence about updating the method `writeIdToConsole` in the `Tracer` class, but I did it for consistency.

adds configurable logging module as argument and defaults to console

---

packages/zipkin-transport-http/src/HttpLogger.js
packages/zipkin-transport-http/test/integrationTest.js

Our problem is that having interval as the only way to control the data sent in HttpLogger is not acceptable for two reasons:
1. We have a limitation that our Zipkin server endpoint can only accept payloads up to a certain size
2. We want to reduce memory consumption of zipkin-js in cases where very large amounts of spans are sent in a short timeframe, which means we need to trigger a send earlier than the interval would otherwise trigger it
The solution is to add an option `maxPayloadSize` to HttpLogger, which will ensure that the send payload will never be larger than the set value in bytes. In case the queue plus the added span would go over the limit, the queue is flushed before the span is added to it. In case a single span itself would go over the limit, then the queue is flushed …

Add support for maxPayloadSize option in HttpLogger.

---

packages/zipkin/src/request.js
packages/zipkin/test/request.test.js

**Why**: on the [discussion about gRPC client](https://github.com/openzipkin/zipkin-js/pull/303#issuecomment-442940269), @jcchavezs brought to my attention I should be sending `X-B3-Flags` if debug is true. I later noticed http were not sending that header either.

send x-b3-flags header with http if debug is true

---

packages/zipkin-instrumentation-grpc-client/.babelrc
packages/zipkin-instrumentation-grpc-client/README.md
packages/zipkin-instrumentation-grpc-client/package.json
packages/zipkin-instrumentation-grpc-client/src/grpcClientInstrumentation.js
packages/zipkin-instrumentation-grpc-client/src/grpcClientInterceptor.js
packages/zipkin-instrumentation-grpc-client/test/.eslintrc
packages/zipkin-instrumentation-grpc-client/test/integrationTest.js
packages/zipkin-instrumentation-grpc-client/test/protos/weather.proto
packages/zipkin-instrumentation-grpc-client/test/utils.js
yarn.lock

**What**: It creates a `grpc` node client interceptor, as [proposed here](https://github.com/grpc/proposal/blob/master/L5-node-client-interceptors.md) and in line with the current [API documentation](https://grpc.io/grpc/node/module-src_client_interceptors.html).
It keeps consistency with the other instrumentation packages in `zipkin-js`, where the tracing must be provided in order to create the interceptor. It will be up to the client generator to abstract it from the end user.
@adriancole please review the annotations and tags being recorded. Am I recording the same as in other languages?
@drobertduke please review it too. I based this work on the interceptors you sent me, but I might be missing something.
cc/ @jcchavezs

adding gRPC client instrumentation

---

packages/zipkin-instrumentation-restify/package.json
packages/zipkin-instrumentation-restify/src/restifyMiddleware.js
yarn.lock

**Why**: Restify instrumentation was not working with `Restify 7.x`
**Cause**: the Restify rewrite in version 7 completely changed how middlewares are executed. Adding `tracer.scoped` call inside the middleware was scoping the changes to inside the middleware and when the test was calling `recordBinary` from the route, it had the original `traceId`. Removing the scope inside the middleware fixed the problem.
**backwards compatibility**: I first made the change with Restify `4.x` and ran the tests. They passed. Only then I upgraded to `7.x`

fix restify instrumentation for restify 7+

---

packages/zipkin/.babelrc
packages/zipkin/package.json
packages/zipkin/src/index.ts

Since #290 is too far behind from the master, I created a new branch so we can start fresh.
We had a problem on #290 that when building the lib, the file extensions weren't been deleted, so if we required a ts file on ```/src```, it will be required when built as well.
Doing some tests, looks like Import and Export statements do this for us, so I think we can do this in order to port zipkin package.

Porting Zipkin package to TypeScript

---

README.md

there was some instrumentation links missing from main README

adding missing package links to main README

---

packages/zipkin/index.d.ts
packages/zipkin/src/instrumentation/httpClient.js
packages/zipkin/src/instrumentation/httpServer.js
packages/zipkin/src/tracer/index.js
packages/zipkin/test/httpClientInstrumentation.test.js
packages/zipkin/test/httpServerInstrumentation.test.js
packages/zipkin/test/trace.test.js

**What**: this is a simple change without contract break to allow the server instrumentation to save default tags at the creation time and record the tags with the request.
**Why**: this gives flexibility for users to set default tags they want recorded.
**The catch**: A few considerations:
1) I decided to send the tags at the constructor, because the `default tags` will already be available at the middleware bootstrap and decided to record them after the `http.path` tag for consistency.
2) why `for..in` instead of using a Map (and for..of) or iterate over the object keys? Well, using the following benchmark:
```javascript
var Benchmark = require('benchmark');
var util = require('util');
var suite = new Benchmark.Suite;
function record(key, val) {
const x = {};
x[key] = val;
}
suite. …
```

recoding default tags on server instrumentation

---

packages/zipkin/src/instrumentation/httpClient.js
packages/zipkin/src/instrumentation/httpServer.js
packages/zipkin/src/tracer/index.js
packages/zipkin/test/httpClientInstrumentation.test.js
packages/zipkin/test/httpServerInstrumentation.test.js
packages/zipkin/test/trace.test.js

removed defaultTags from http server and client instrumentation.
@jcchavezs let me know if this works for you...

moving defaultTags to tracing (remove from http server and client)

---

.travis.yml
packages/zipkin/karma.conf.js
packages/zipkin/package.json
packages/zipkin/test/batch-recorder.test.js
test/helper.js
yarn.lock

Fix for #313. The setup works as follows:
- If `TEST_SUITE` env var is set to `nodejs`, then the mocha tests run
- If `TEST_SUITE` env var is set to `browser` then the karma tests run
- If `TEST_SUITE`env var is not set, then both suites run
A 3rd entry is added to the test matrix for `browser` in the CI runs which only runs the browser tests.
Note that there is a single test that was previously failing under the browser (unrelated to this change). I'm opening a separate issue to address this, but do not believe this should be a blocker in merging this PR.

run tests for zipkin library under karma #313

---

package.json

With the upgrade of lerna, this script for releasing got outdated. There is an [issue](https://github.com/openzipkin/zipkin-js/issues/316) to prevent this in the future.
Ping @ghermeto.

fix: fixes lerna script for releasing.

---

README.md

This updates the `README` file to be more explicit about which parts of this project are available for node.js and the browser. This addresses #54 and is the first task in #311.

update readme to be more specific about browser vs nodejs support #54

---

packages/zipkin-instrumentation-express/src/expressMiddleware.js
packages/zipkin-instrumentation-express/test/expressMiddlewareIntegrationTest.js

**Why?** the tracer scoped inside the middleware was preventing the traceId to be accessed from sequential promises in the route handler.
@jcchavezs I added a test that verifies that the tracerId will remains the same within the same request, but will be different on subsequent requests.

Fix express middleware - fixes #318

---

packages/zipkin-instrumentation-express/src/expressMiddleware.js
packages/zipkin-instrumentation-express/test/expressMiddlewareIntegrationTest.js

adds route.path to rpc when possible. In express if the request
is terminated in the middleware (like in express-http-proxy)
the request won't have the route property set.
cc/ @adriancole @jcchavezs 
this replaces #200

adds route.path to express instrumentation

---

packages/zipkin-instrumentation-redis/src/zipkinClient.js
packages/zipkin-instrumentation-redis/test/integrationTest.js

The tracing of single commands do not record the payload but batched commands include it.
For many commands with big payloads this can end up becoming several megabytes of annotation information.
This commit removes it for batched commands as well.

Do not send redis command payloads

---

packages/zipkin-instrumentation-grpc-client/package.json

I had included zipkin-instrumentation-grpc-client using npm install
`npm install zipkin-instrumentation-grpc-client@0.15.0 --save`
On running the application, I get the error
`Error: Cannot find module 'zipkin-instrumentation-grpc-client' at Function.Module._resolveFilename (module.js:547:15) at Function.Module._load (module.js:474:25) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at Object.<anonymous> (/Users/300027553/Work/wit/mwpserver/server/grpc/client/workouts.js:5:1) at Module._compile (module.js:652:30) at loader (/Users/300027553/Work/wit/mwpserver/node_modules/babel-register/lib/node.js:144:5) at Object.require.extensions.(anonymous function) [as .js] (/Users/300027553/Work/wit/mwpserver/node_modules/babel-register/lib/node.js:154:7) at Module.load …

Updated main file in package zipkin-instrumentation-grpc-client

---

packages/zipkin-transport-http/package.json

Upgraded the node-fetch version to 2.3.0 in zipkin-transport-http.
We are getting build warning  from react application because of this old dependency.

Upgraded the node-fetch version to 2.3.0 in zipkin-transport-http

---

packages/zipkin-instrumentation-fetch/src/wrapFetch.js
packages/zipkin-instrumentation-fetch/test/integrationTest.js

The [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Parameters) defines the first argument as being either of the type `USVString` or `Request`. The current implementation of `zipkin-instrumentation-fetch` however only accepts a string; causing a `TypeError` to be thrown if a `Request` is passed.

Fix fetch signature

---

package.json
packages/zipkin/rollup.config.js
packages/zipkin/src/index.ts
yarn.lock

This PR fixes the Zipkin bundle execution in the browser. The current bundle has two main issues:
* it is using the `global` variable, which isn't (yet) defined in browsers
* it is exporting the Zipkin values using `module.exports`.
See: https://jsbin.com/wuzeqetezi/edit?html,output

Fix the browser bundle

---

.travis.yml

This PR enables node 10 in the CI.
Ping @openzipkin/zipkin-js-champions @ghermeto

Node 10 support

---

.travis.yml

Comes from #338 
Ping @openzipkin/zipkin-js-champions

chore(#338): Removes support for node 6 in travis.

---

packages/zipkin-instrumentation-request/src/wrapRequest.js
packages/zipkin-instrumentation-request/test/integrationTest.js

httpclient.recordResponse must be called inside of tracer.scoped otherwise it mutates the current context. This causes spans to have the wrong parent. 
This pattern is used in the other packages already [restInterceptor](https://github.com/openzipkin/zipkin-js/blob/a8ab73d26157a3b25b207425e2808ee39105afa1/packages/zipkin-instrumentation-cujojs-rest/src/restInterceptor.js#L29-L31), [express](https://github.com/openzipkin/zipkin-js/blob/001306fc9bbd017553be8b9db84f322efdebbe20/packages/zipkin-instrumentation-express/src/expressMiddleware.js#L54-L61), [connect](https://github.com/openzipkin/zipkin-js/blob/55f461eb14753658fdb3f64cab883d8668f31b4c/packages/zipkin-instrumentation-connect/src/middleware.js#L67)

Fix tracer context for zipkin-instrumentation-request

---

packages/zipkin/src/console-recorder.js

Adding Timestamp to the Console Recorder Logger to record time across multiple requests.

Updating Timestamp in Console Recorder

---

packages/zipkin/index.d.ts

As far as I can see from [index.js](https://github.com/openzipkin/zipkin-js/blob/00604b73d938b25b36a754765cdcca435def1b07/packages/zipkin/src/tracer/index.js#L31), `supportsJoin` is a valid argument, so this PR reflects this in the typed arguments. 
Thank you for the awesome library!

Reflect supportsJoin agument parameter in types

---

packages/zipkin-instrumentation-axios/src/index.js
packages/zipkin-instrumentation-axios/test/integrationTest.js
packages/zipkin-instrumentation-axios/test/unitTest.js
packages/zipkin-instrumentation-axios/test/utils.js

- pass traceId from request to response by config, traceId will change after record request
- avoid dirty `axios`, create an axios instance before using interceptors

#348 pass traceId from request to response

---

test/helper.js

Before, the assertion failure that mocha could readily interpret was
wrapped when inside an async hook. This made for very not helpful
failures.
This unwraps to prevent this.
before:
```
(node:70680) UnhandledPromiseRejectionWarning: AssertionError: expected { Object (http.path, http.status_code) } to deeply equal { Object (http.path, http.status_code) }
```
after:
```
1) axios instrumentation - integration test
should support request shorthand (defaults to GET):
Uncaught AssertionError: expected { Object (http.path, http.status_code) } to deeply equal { Object (http.path, http.status_code) }
+ expected - actual
{
"http.path": "/weather/wuhan"
-  "http.status_code": "202"
+  "http.status_code": "2022"
}
```
See https://github.com/mochajs/mocha/issues/2797

Shows object diff when an async assertion fails

---

packages/zipkin-instrumentation-axiosjs/test/integrationTest.js
packages/zipkin-instrumentation-axiosjs/test/utils.js

Step 1: make the request headers test do what it says it does

Refactors Axios unit tests

---

karma.conf.js
package.json
packages/zipkin-context-cls/package.json
packages/zipkin-encoder-thrift/package.json
packages/zipkin-instrumentation-axiosjs/package.json
packages/zipkin-instrumentation-axiosjs/src/index.js
packages/zipkin-instrumentation-axiosjs/test/integrationTest.js
packages/zipkin-instrumentation-axiosjs/test/unitTest.js
packages/zipkin-instrumentation-connect/package.json
packages/zipkin-instrumentation-cujojs-rest/package.json
packages/zipkin-instrumentation-express/package.json
packages/zipkin-instrumentation-fetch/package.json
packages/zipkin-instrumentation-got/package.json
packages/zipkin-instrumentation-grpc-client/package.json
packages/zipkin-instrumentation-hapi/package.json
packages/zipkin-instrumentation-kafkajs/package.json
packages/zipkin-instrumentation-memcached/package.json
packages/zipkin-instrumentation-postgres/package.json
packages/zipkin-instrumentation-redis/package.json
packages/zipkin-instrumentation-request-promise/package.json
packages/zipkin-instrumentation-request/package.json
packages/zipkin-instrumentation-restify/package.json
packages/zipkin-instrumentation-superagent/package.json
packages/zipkin-transport-http/package.json
packages/zipkin-transport-kafka/package.json
packages/zipkin-transport-scribe/package.json
packages/zipkin/package.json
test/middleware.js
test/testFixture.js
yarn.lock

This extracts middleware such that axios tests can execute normally and also
in browser with Karma. It also swaps assertion style to v2 for clarity.

Rewrite axios integration tests to use v2 syntax and also execute in browser

---

packages/zipkin-instrumentation-axiosjs/test/integrationTest.js
packages/zipkin-instrumentation-cujojs-rest/package.json
packages/zipkin-instrumentation-cujojs-rest/test/integrationTest.js
test/testFixture.js

This refactors tests so that spans look more like literals. It also
pulls up some common logic. Finally, this backfills tests that pass
on cujojs-rest

Refactors client integration tests slightly and backfills cujojs-rest

---

packages/zipkin/src/batch-recorder.js

If a span has no startTimestamp timeout checks should not apply.
Problem with spans with no timestamp is that the UI can't render it.
Ping @adriancole

fix: checks if there is a start timestamp to properly detect timeout.

---

packages/zipkin-instrumentation-axiosjs/test/integrationTest.js
packages/zipkin-instrumentation-cujojs-rest/test/integrationTest.js
packages/zipkin/src/batch-recorder.js
packages/zipkin/test/batch-recorder.integrationTest.js
test/testFixture.js

There were some red herrings about an example failing. This carves out
a unit test for people to fill for suspected problems.

Backfills integrated tests of BatchRecorder

---

packages/zipkin/src/batch-recorder.js
packages/zipkin/src/tracer/index.js
packages/zipkin/test/batch-recorder.integrationTest.js
packages/zipkin/test/batch-recorder.test.js

Before, we conflated timing around data timeouts with span lifecycle
(eg start/finish). This caused some confusion in the code, and a lot of
redundant clock calls. This refactors the code to only use timestamps
from the events, and only the authoritative ones for purposes of start
and finish.
Moreover, this attempts to compensate for data lost when a flush happens
between start and finish by backfilling a "finish" annotation in such
case. With better code structure in finish callbacks, we should even be
able to eliminate this (by redundantly replaying the span's start event
on an async finish callback). For now, it will correct the problems of
flush better than most libraries do, because the UI will interpret any
annotation to backfill a duration.

Fixes various timestamp problems, notably when a span is flushed

---

packages/zipkin-instrumentation-axiosjs/README.md
packages/zipkin-instrumentation-axiosjs/test/integrationTest.js
packages/zipkin-instrumentation-axiosjs/test/unitTest.js
packages/zipkin-instrumentation-connect/test/integrationTest.js
packages/zipkin-instrumentation-cujojs-rest/test/integrationTest.js
packages/zipkin-instrumentation-express/README.md
packages/zipkin-instrumentation-express/src/wrapExpressHttpProxy.js
packages/zipkin-instrumentation-express/test/expressMiddlewareIntegrationTest.js
packages/zipkin-instrumentation-express/test/wrapExpressHttpProxyIntegrationTest.js
packages/zipkin-instrumentation-fetch/test/integrationTest.js
packages/zipkin-instrumentation-got/test/integrationTest.js
packages/zipkin-instrumentation-hapi/test/integrationTest.js
packages/zipkin-instrumentation-request/test/integrationTest.js
packages/zipkin-instrumentation-restify/test/integrationTest.js
packages/zipkin/index.d.ts
packages/zipkin/test/httpServerInstrumentation.test.js

We continue to get support problems due to people overriding service
names incorrectly. There's rarely a valid reason to override what's in
the tracer. This stops us from doing it in tests and README files. We
should strongly consider removing the ability to override the
serviceName in v2 such as we do in other libraries, for the reason of
needless support burden.

Stops encouraging serviceName overrides

---

packages/zipkin-instrumentation-kafkajs/package.json
packages/zipkin-instrumentation-kafkajs/test/integrationTest.js
packages/zipkin-instrumentation-request-promise/src/request.js

We have almost no usage of lodash, and the usage we have isn't security
critical. This removes the lodash dependency to avoid having to look up
what unrelated problems exist when there's a security notice.
See #390
Fixes #391

Removes lodash to avoid distracting bot pull requests

---

packages/zipkin-instrumentation-fetch/package.json
packages/zipkin-instrumentation-fetch/test/integrationTest.js

This migrates the same tests used in Axios to fetch, notably deferring
loading of node-fetch in case we are running in a browser.

Migrates fetch to v2 style assertions and ensures they run in a browser

---

packages/zipkin/index.d.ts
packages/zipkin/src/tracer/index.js
packages/zipkin/test/trace.test.js

The initial design of zipkin-js included a sentinel value on `Tracer.id`
that allows you to avoid needing to compare against null. The trouble is
that the sentinel was never compared against, and would result in root
spans appearing to be children of the sentinel. This is a bug because it
can lead to very large pseudo-traces. I'm sure the intent was to check
the sentinel before using it.

Fixes bug where Tracer.id sentinel value was ignored

---

packages/zipkin-instrumentation-request/package.json
packages/zipkin-instrumentation-request/test/integrationTest.js

Note: this removes the promisify test as it isn't relevant. We now have
a request-promise module, which I'll port shortly.

Rewrites request tests to v2 style

---

packages/zipkin-instrumentation-superagent/package.json
packages/zipkin-instrumentation-superagent/src/superagentPlugin.js
packages/zipkin-instrumentation-superagent/test/integrationTest.js

We were calling finish twice on 4xx and 5xx and didn't notice.

Fixes double-recording bug in superagent and rewrites tests to v2

---

packages/zipkin-instrumentation-axiosjs/package.json
packages/zipkin-instrumentation-cujojs-rest/package.json
packages/zipkin-instrumentation-fetch/package.json
packages/zipkin-instrumentation-gotjs/package.json
packages/zipkin-instrumentation-grpc-client/package.json
packages/zipkin-instrumentation-kafkajs/package.json
packages/zipkin-instrumentation-memcached/README.md
packages/zipkin-instrumentation-memcached/package.json
packages/zipkin-instrumentation-memcached/src/zipkinClient.js
packages/zipkin-instrumentation-memcached/test/integrationTest.js
packages/zipkin-instrumentation-request-promise/package.json
packages/zipkin-instrumentation-request/package.json
packages/zipkin-instrumentation-superagent/package.json

This fixes the span name of get-multi and the lack of error recording on
memcached instrumentation. I noticed these problems when porting tests
v2 style.

Fixes naming of get-multi and lack of error recording on memcached

---

packages/zipkin-instrumentation-postgres/package.json
packages/zipkin-instrumentation-postgres/src/zipkinClient.js
packages/zipkin-instrumentation-postgres/test/integrationTest.js

There were a couple glitches notably port being tagged as a number, not
a string, and error being toString instead of preferring the message.
This was easy to see when the tests were ported to json v2.
Future work needs to happen because this code is unlike other database
instrumentation in so far as the span name is constant and there are no
tags except error.

Fixes some data glitches in postgres and converts tests to v2

---

packages/zipkin-instrumentation-express/package.json
packages/zipkin-instrumentation-hapi/package.json
packages/zipkin-instrumentation-hapi/src/hapiMiddleware.js
packages/zipkin-instrumentation-hapi/test/integrationTest.js
packages/zipkin-instrumentation-restify/package.json
yarn.lock

Before, the current trace ID was not available during the route handler method. This would cause outgoing requests to be a part of the wrong trace.

Fixes hapi trace scoping and ports tests to v2

---

packages/zipkin/index.d.ts

please spin me a new release when you can.   I need this for a project at work.  it's just an option constructor argument in the Tracer type so we can pass the defaultTags.  I tested that it works.. i see my tags in all the traces ;)
closes https://github.com/openzipkin/zipkin-js/issues/413

add defaultTags to Tracer type

---

packages/zipkin-instrumentation-axiosjs/test/integrationTest.js
packages/zipkin-instrumentation-cujojs-rest/test/integrationTest.js
packages/zipkin-instrumentation-fetch/test/integrationTest.js
packages/zipkin-instrumentation-gotjs/test/integrationTest.js
packages/zipkin-instrumentation-request-promise/test/integrationTest.js
packages/zipkin-instrumentation-request/test/integrationTest.js
packages/zipkin-instrumentation-superagent/test/integrationTest.js
test/testFixture.js

This starts to pare down test duplication by extracting out a facet that
manages the start and stop of middleware used in client integration
tests.
Installation should be like this
```javascript
const {setupTestServer} = require('../../../test/testFixture');
const server = setupTestServer();
```
Later, you can get a url for clients to use via `server.url(path)`
See https://github.com/mochajs/mocha/wiki/Shared-Behaviours

Uses mocha shared behaviors to setup client integration test middleware

---

packages/zipkin/index.d.ts
packages/zipkin/src/batch-recorder.js
packages/zipkin/test/batch-recorder.test.js

This PR adds a `flush` method for http reporter.
Closes #362 
Ping @CSP197 @adriancole

feat(#362): adds flush method to http reporter.

---

packages/zipkin-instrumentation-axiosjs/test/integrationTest.js
packages/zipkin-instrumentation-connect/src/middleware.js
packages/zipkin-instrumentation-connect/test/integrationTest.js
packages/zipkin-instrumentation-cujojs-rest/test/integrationTest.js
packages/zipkin-instrumentation-express/src/expressMiddleware.js
packages/zipkin-instrumentation-express/src/wrapExpressHttpProxy.js
packages/zipkin-instrumentation-express/test/expressMiddlewareIntegrationTest.js
packages/zipkin-instrumentation-express/test/testMiddleware.js
packages/zipkin-instrumentation-express/test/wrapExpressHttpProxyIntegrationTest.js
packages/zipkin-instrumentation-fetch/test/integrationTest.js
packages/zipkin-instrumentation-gotjs/test/integrationTest.js
packages/zipkin-instrumentation-grpc-client/test/integrationTest.js
packages/zipkin-instrumentation-hapi/test/integrationTest.js
packages/zipkin-instrumentation-kafkajs/test/integrationTest.js
packages/zipkin-instrumentation-memcached/test/integrationTest.js
packages/zipkin-instrumentation-postgres/test/integrationTest.js
packages/zipkin-instrumentation-redis/test/integrationTest.js
packages/zipkin-instrumentation-request-promise/src/request.js
packages/zipkin-instrumentation-request-promise/test/integrationTest.js
packages/zipkin-instrumentation-request/test/integrationTest.js
packages/zipkin-instrumentation-restify/src/restifyMiddleware.js
packages/zipkin-instrumentation-restify/test/integrationTest.js
packages/zipkin-instrumentation-superagent/test/integrationTest.js
test/testFixture.js

This ports all the instrumentation packages. There is still some porting opportunities in the reporters and the base module itself. However, this is a good place to stop for a bit.

Extracts a tracer fixture to remove copy/paste and fixes scoping problems in instrumentation

---

packages/zipkin-instrumentation-axiosjs/test/integrationTest.js
packages/zipkin-instrumentation-cujojs-rest/src/restInterceptor.js
packages/zipkin-instrumentation-cujojs-rest/test/integrationTest.js
packages/zipkin-instrumentation-fetch/test/integrationTest.js
packages/zipkin-instrumentation-gotjs/test/integrationTest.js
packages/zipkin-instrumentation-request-promise/test/integrationTest.js
packages/zipkin-instrumentation-request/test/integrationTest.js
packages/zipkin-instrumentation-superagent/test/integrationTest.js
test/httpClientTestFixture.js

By using a common http client test fixture, we can remove needless difference between instrumentation tests. This makes it easy to spot and correct missing tests, and also easier to identify special behaviors.

Creates common fixture for http client test

---

packages/zipkin-instrumentation-connect/test/integrationTest.js
packages/zipkin-instrumentation-express/test/expressMiddlewareIntegrationTest.js
packages/zipkin-instrumentation-express/test/wrapExpressHttpProxyIntegrationTest.js
packages/zipkin-instrumentation-fetch/test/integrationTest.js
packages/zipkin-instrumentation-hapi/test/integrationTest.js
packages/zipkin-instrumentation-kafkajs/test/integrationTest.js
packages/zipkin-instrumentation-restify/test/integrationTest.js
test/httpClientTestFixture.js
test/testFixture.js

We should only use beforeEach when state is required, but not known
until test execution (ex test name). Otherwise, it is distracting.
This removes unnecessary beforeEach and related lazy instantiation
from integration tests.

Reduces unnecessary use of beforeEach hooks in integration tests

---

packages/zipkin-instrumentation-axiosjs/test/integrationTest.js
packages/zipkin-instrumentation-cujojs-rest/test/integrationTest.js
packages/zipkin-instrumentation-fetch/test/integrationTest.js
packages/zipkin-instrumentation-gotjs/test/integrationTest.js
packages/zipkin-instrumentation-request-promise/test/integrationTest.js
packages/zipkin-instrumentation-request/test/integrationTest.js
packages/zipkin-instrumentation-superagent/test/integrationTest.js
test/httpClientTestFixture.js
test/middleware.js

Of course, the abandoned CujoJS has no setting to disable redirects.

Adds http client test for redirects

---

packages/zipkin-instrumentation-kafkajs/README.md

Fix required package name from the code example.

Fix typo for zipkin-instrumentation-kafkajs

---

.eslintignore
package.json
packages/zipkin-transport-http/index.d.ts
packages/zipkin-transport-http/src/HttpLogger.js
packages/zipkin-transport-http/test-types/HttpLogger.test.ts

Provide option to set a custom agent to use with node-fetch.
https://www.npmjs.com/package/node-fetch#custom-agent
This will allow users to specify any networking related options. For example, users can provide client certificates to hit mTLS endpoints, or CA certificates to use self-signed certificates.
Will use default agent if no agent option passed.

Added agent option to http transport

---

packages/zipkin-instrumentation-express/src/expressMiddleware.js
packages/zipkin/src/batch-recorder.js
packages/zipkin/test/batch-recorder.test.js

This PR fixes a comparison with `undefined` and also adds a guard for `partial spans` that have not `timestamp` attribute (because they were already reported).
Ping @adriancole

fix: fixes undefined comparison and partial span timeout rules.

---

packages/zipkin/src/InetAddress.js
packages/zipkin/test/InetAddress.test.js

When profiling an express app using the zipkin express instrumentation, I noticed that for each request, around 15ms is being spent in `os.networkInterfaces()` . From reading the code, it looks like this only happens if no `host` is provided to the `HttpServerInstrumentation` class (if a host is provided when this class is instantiated, for each invocation of `recordRequest`, we don't need to look at the available network interfaces).
This is because the current fallback behaviour when no `host` is provided is to call [`InetAddress.getLocalAddress()`](https://github.com/jdb8/zipkin-js/blob/e65652100fd31ed41425e255f58b60e51a01602a/packages/zipkin/src/InetAddress.js#L34) each time [a new `LocalAddr` is created](https://github.com/jdb8/zipkin-js/blob/e65652100fd31ed41425e255f58b60e51a01602a/p …

Call getLocalAddress() in HttpServerInstrumentation constructor

---

LICENSE

License itself could be anything else you choose of course. Submitting with MIT because this is the one I always use when given a choice.
Fixes #463

chore(legal): adds MIT license

---

packages/zipkin-instrumentation-hapi/src/hapiMiddleware.js

server.decorate seems to only allow adding methods to the server, request, or toolkit, not wrapping. So this comment is probably not correct.

Remove comment about server.decorate

---

packages/zipkin-transport-http/README.md
packages/zipkin-transport-http/package.json
packages/zipkin-transport-http/src/HttpLogger.js
packages/zipkin-transport-http/test/integrationTest.js
yarn.lock

Defaults to an exponential backoff with retrying always and forever.
All options are configurable through the constructor of the
HttpLogger class.
Goal: Do not lose traces if there was an intermittent network
connectivity issue in a browser environment for example.
Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

feat(zipkin-transport-http): configurable retry

---

packages/zipkin-instrumentation-express/package.json
packages/zipkin-instrumentation-express/test/concurrentTest.js
yarn.lock

Adds a test for concurrent request that ensures that content is correctly preserved over promises when using cls-hooked. 
If you change 
```
ctxImpl = new CLSContext('zipkin', true); 
```
to 
```
ctxImpl = new CLSContext('zipkin', false);
```
the test will fail.

tests: adds test to verify context during concurrent request

---

packages/zipkin-transport-http/src/HttpLogger.js

This PR adds a fallback value to fetch when `this` loses context.
I wasn't able to add any kind of tests to verify this change, but the existing ones still pass. 
Closes https://github.com/openzipkin/zipkin-js/issues/493

feat(http): add fallback for fetch

---

packages/zipkin-context-cls/src/CLSContext.js
packages/zipkin-context-cls/test/CLSContext.test.js

I noticed that the existing test `supports async-await contexts` passes even if you disable the async await support on line 98.
I then tried to update this using an EventEmitter as I did in my other PR to more reliably reproduce the concurrent request behavior and was a bit surprised to discover that even with cls-hooked the test failed.   
It appears that when using an EventEmitter you need to explicitly register it with cls-hooked and when I did that it passed.  I then discovered that cls-continuation-context also supported a bindEmitter method and after exposing bindEmitter on context the test would pass in either implementation.  
I'm a bit sad it was necessary to explicitly register the emitter as I had hoped that when using async-hooks anything created within the context of an …

Expose bindEmitter on CLSContext

---

packages/zipkin-context-cls/.babelrc
packages/zipkin-context-cls/README.md
packages/zipkin-context-cls/package.json
packages/zipkin-context-cls/src/CLSContext.js
packages/zipkin-context-cls/test/CLSContext.test.js
packages/zipkin-instrumentation-express/package.json
packages/zipkin-instrumentation-express/test/concurrentTest.js
yarn.lock

This PR adds support for `async` compatibility in CLS Context, using `cls-hooked` underneath and allowing users to opt-in this due to some [performance implications](https://github.com/DataDog/dd-trace-js/issues/695) for `cls-hooked` (update on readme needed).
**Why not a new package instead of adding it into existing package?**
In my mind `async` support is a feature on top of existing CLS package, it does not provide a fundamentally different functionality than it does already does but for modern versions of ES. In addition, it might become yet another package to support that is literally the same as CLS but with another library underneath.
**What about the performance implications in async_hooks**
This is already visible among node people and the situation [improved from node 8 to …

feat: adds support for cls-hooked.

---

packages/zipkin-instrumentation-request-promise/package.json
packages/zipkin-transport-http/README.md
packages/zipkin-transport-http/package.json
yarn.lock

I moved libraries which are required in code in deps from devDeps and add commas to readme.
Closes https://github.com/openzipkin/zipkin-js/issues/491

Deps correctness

---

packages/zipkin-transport-http/package.json

Since the fetch implementation is figured out at runtime as described [here](https://github.com/openzipkin/zipkin-js#typescript).
I'd like to add the `"browser"` field to the `package.json` too in order to fix bundlers like webpack.
You can see more about the [`"browser"` field here](https://github.com/defunctzombie/package-browser-field-spec).
In short, this is a better fix than modifying (in my case non-existent) `tsconfig.json`

Fix: Module not found: node-fetch

---

packages/zipkin/index.d.ts

The definition for `createNoobTracer()` in `index.d.ts` says that I should expect a void return.
But looking at the code that's obviously incorrect.
The hints that are created using index.d.ts
The source code for `createNoopTracer` that always return a Tracer
Currently a workaround for proper typings in TypeScript is:
```ts
return <unknown>createNoopTracer() as Tracer;
```

Fix: Return of createNoopTracer is void
