- .travis.yml
http://stackoverflow.com/questions/37558151/travis-ci-build-failing
> try to fix travis build

- packages/zipkin-instrumentation-fetch/src/wrapFetch.js
- packages/zipkin-instrumentation-fetch/test/integrationTest.js
Fixes https://github.com/openzipkin/zipkin-js/issues/11
> add default options to fetch wrapper

- appveyor.yml
> WIP: appveyor build

- packages/zipkin-transport-http/src/HttpLogger.js
- packages/zipkin/src/batch-recorder.js
> Guards timer.unref for browsers who might not have it

- packages/zipkin-instrumentation-hapi/README.md
- packages/zipkin-instrumentation-hapi/index.js
- packages/zipkin-instrumentation-hapi/package.json
- packages/zipkin-instrumentation-hapi/src/hapiMiddleware.js
- packages/zipkin-instrumentation-hapi/test/.eslintrc
- packages/zipkin-instrumentation-hapi/test/integrationTest.js
Fixes https://github.com/openzipkin/zipkin-js/issues/43
> Add new instrumentation: hapi

- .travis.yml
- README.md
- appveyor.yml
- packages/zipkin-instrumentation-redis/README.md
- packages/zipkin-instrumentation-redis/package.json
- packages/zipkin-instrumentation-redis/src/zipkinClient.js
- packages/zipkin-instrumentation-redis/test/.eslintrc
- packages/zipkin-instrumentation-redis/test/integrationTest.js
> Adds zipkin-instrumentation-redis support

- packages/zipkin-instrumentation-hapi/src/hapiMiddleware.js
- packages/zipkin-instrumentation-hapi/test/integrationTest.js
Fixes #61. 
Not sure if what I'm doing here is okay. In order to split the span actions into two callbacks, I'm storing the trace on the request object and then reattaching it to the context in the response hook. 
@adriancole @eirslett
> Fix incorrect span durations when using hapi.js middleware

- packages/zipkin-instrumentation-restify/src/restifyMiddleware.js
See this: https://github.com/nodejs/node/issues/6929
> Listen for both close or finish

- packages/zipkin-instrumentation-request/README.md
Small correction to the usage of request/require.
> Correction to README

- packages/zipkin-transport-scribe/test/integrationTest.js
- packages/zipkin/src/internalRepresentations.js
> Fix ServerAddr UInt8Array to Buffer for thrift

- packages/zipkin-transport-http/src/HttpLogger.js
- packages/zipkin/src/InetAddress.js
Fixes #114 
@adriancole Could you take a look?
> Remove unnecessary node core dependencies

- packages/zipkin/README.md
- packages/zipkin/index.d.ts
- packages/zipkin/package.json
I started using this in our project. This is by no means complete and may contain some errors. But! It still helps immensely when adding custom integrations (if you use TypeScript that is).
Related to:
- https://github.com/openzipkin/zipkin-js/issues/13
- https://github.com/openzipkin/zipkin-js/issues/28
> First go at typescript type definitions

- packages/zipkin-transport-http/index.d.ts
- packages/zipkin-transport-http/package.json
- packages/zipkin-transport-kafka/index.d.ts
- packages/zipkin-transport-kafka/package.json
- packages/zipkin-transport-scribe/index.d.ts
- packages/zipkin-transport-scribe/package.json
- packages/zipkin/index.d.ts
- yarn.lock
Here are some more typescript declarations
> Typescript transport declarations

- packages/zipkin/index.d.ts
Mostly updating after #137 and #142 changes
Additionally add:
- sampler namespace
- Record interface
- TraceId properties
> Update type definitions

- .travis.yml
- README.md
- appveyor.yml
- packages/zipkin-instrumentation-postgres/README.md
- packages/zipkin-instrumentation-postgres/package.json
- packages/zipkin-instrumentation-postgres/src/zipkinClient.js
- packages/zipkin-instrumentation-postgres/test/.eslintrc
- packages/zipkin-instrumentation-postgres/test/integrationTest.js
Resolves https://github.com/openzipkin/zipkin-js/issues/149
> Add postgres instrumentation

- packages/zipkin/README.md
- packages/zipkin/index.d.ts
- packages/zipkin/package.json
- packages/zipkin/src/annotation.js
- packages/zipkin/src/batch-recorder.js
- packages/zipkin/src/tracer/index.js
- packages/zipkin/test/trace.test.js
Inspired by the same design in https://github.com/openzipkin/zipkin4net 
Fixes #104
> Adds Tracer.local for local tracing

- packages/zipkin/src/tracer/index.js
- packages/zipkin/test/trace.test.js
Fixes a bad bug if you actually used the local tracing with a promise. I noticed found this using the react-native example. Immediate patch release to follow merge.
> Closes the correct span on promise complete

- packages/zipkin-transport-http/package.json
> Remove chai from transport-http dependencies

- .gitignore
- packages/zipkin/src/instrumentation/httpServer.js
- packages/zipkin/test/httpServerInstrumentation.test.js
This PR aims to add support for tracing flags in zipkin-js.
Ping @adriancole @fbaiodias @pchiwan
Closes #197
> [#197] Adds support for sampling flags extraction.

- .gitignore
- README.md
This PR adds the npm badge to the readme
> Adds NPM package badge.

- packages/zipkin/src/instrumentation/httpServer.js
- packages/zipkin/test/httpServerInstrumentation.test.js
Link to the issue: https://github.com/openzipkin/zipkin-js/issues/236
> Allow host to be overridden in httpServer instrumentation (#236)

- packages/zipkin/src/instrumentation/httpServer.js
- packages/zipkin/src/tracer/index.js
- packages/zipkin/test/httpServerInstrumentation.test.js
> [#197] Improves sampling flags testing with meaningful cases.

- packages/zipkin/src/model.js
- packages/zipkin/test/model.test.js
> Ensure tag values are strings in JSON V2

- packages/zipkin/index.d.ts
- packages/zipkin/src/index.js
- packages/zipkin/src/option.js
Fix some types, remove exposed private fields,
expose some useful and / or forgotten methods / classes.
Addresses #212
> Improve TS interface

- packages/zipkin-context-cls/README.md
> Added troubleshooting for body-parser problem

- packages/zipkin-instrumentation-express/src/expressMiddleware.js
- packages/zipkin-instrumentation-request-promise/test/integrationTest.js
- packages/zipkin-instrumentation-request/test/integrationTest.js
- packages/zipkin-instrumentation-restify/src/restifyMiddleware.js
- packages/zipkin/src/instrumentation/httpClient.js
- packages/zipkin/src/instrumentation/httpServer.js
- packages/zipkin/test/httpClientInstrumentation.test.js
This PR makes it possible to to add errors based on status code for http instrumentations.
Ping @adriancole @mkante @DanielMSchmidt
> feat: adds error based on status code for http instrumentation.

- packages/zipkin-instrumentation-request-promise/test/integrationTest.js
This PR is a follow up of issue #189 
I added more tests to support feature/issue-179
> Backfill tests for 4xx or 5xx status code

- .gitignore
- package-lock.json
This PR adds the `package-lock.json` and removes it from `.gitignore`.
> chore: Commits package-lock.json.

- packages/zipkin/src/InetAddress.js
> changing import to network file

- .travis.yml
> Droping node 4 support

- packages/zipkin-instrumentation-superagent/.babelrc
- packages/zipkin-instrumentation-superagent/README.md
- packages/zipkin-instrumentation-superagent/package.json
- packages/zipkin-instrumentation-superagent/src/superagentPlugin.js
- packages/zipkin-instrumentation-superagent/test/.eslintrc
- packages/zipkin-instrumentation-superagent/test/integrationTest.js
- packages/zipkin-instrumentation-superagent/test/superagentPluginTest.js
- packages/zipkin-instrumentation-superagent/test/utils.js
- yarn.lock
> adding superagent instrumentation

- packages/zipkin-instrumentation-restify/src/restifyMiddleware.js
1) using `bind` is slower compared with other methods:
The following test:
```javascript
var Benchmark = require('benchmark');
var suite = new Benchmark.Suite;
class Some {
constructor(val) {
this.val = val;
}
}
class None {}
const req = {
headers: { foo: 'bar' },
header(name) {
return this.headers[name];
}
};
function headerOption(request, header) {
const val = request.header(header);
if (val != null) {
return new Some(val);
} else {
return None;
}
}
suite.
add('redefining', function() {
function readHeader(header) {
const val = req.header(header);
if (val != null) {
return new Some(val);
} else {
return None;
}
}
return readHeader('foo');
}).
add('binding', function() {
const readHeader = headerOption.bind(null, req);
return readHeader('foo');
}).
add('wrapping', function() {
const …
```
> small performance improvements for restify middleware

- packages/zipkin/src/instrumentation/httpServer.js
- packages/zipkin/src/tracer/index.js
- packages/zipkin/test/httpServerInstrumentation.test.js
- packages/zipkin/test/trace.test.js
> httpServer instrumentation should let sampler to make decision if missing sampled header

- packages/zipkin/test/trace.test.js
> fix: fixes lint.

- README.md
I found this important during refactoring
> Adds docs to only test a single module

- packages/zipkin/src/batch-recorder.js
Reverts openzipkin/zipkin-js#377
> Revert "fix: checks if there is a start timestamp to properly detect timeout."

- README.md
- package.json
- packages/zipkin-context-cls/package.json
- packages/zipkin-encoder-thrift/package.json
- packages/zipkin-instrumentation-axiosjs/package.json
- packages/zipkin-instrumentation-connect/package.json
- packages/zipkin-instrumentation-cujojs-rest/package.json
- packages/zipkin-instrumentation-express/package.json
- packages/zipkin-instrumentation-fetch/package.json
- packages/zipkin-instrumentation-got/package.json
- packages/zipkin-instrumentation-grpc-client/package.json
- packages/zipkin-instrumentation-hapi/package.json
- packages/zipkin-instrumentation-kafkajs/package.json
- packages/zipkin-instrumentation-memcached/package.json
- packages/zipkin-instrumentation-postgres/package.json
- packages/zipkin-instrumentation-redis/package.json
- packages/zipkin-instrumentation-request-promise/package.json
- packages/zipkin-instrumentation-request/package.json
- packages/zipkin-instrumentation-restify/package.json
- packages/zipkin-instrumentation-superagent/package.json
- packages/zipkin-transport-http/package.json
- packages/zipkin-transport-kafka/package.json
- packages/zipkin-transport-scribe/package.json
- packages/zipkin/package.json
You can view the README render here https://github.com/openzipkin/zipkin-js/blob/debugger-instructions/README.md#debugging
> Adds debugger instructions as probably few know how to do this

- README.md
> docs: adds tweaks to readme.

- packages/zipkin-instrumentation-redis/package.json
- packages/zipkin-instrumentation-redis/src/zipkinClient.js
- packages/zipkin-instrumentation-redis/test/integrationTest.js
There are still some data problems here, but they can be addressed
separately.
> Fixes redis error handling and ports tests to v2

- packages/zipkin-instrumentation-axiosjs/test/integrationTest.js
- packages/zipkin-instrumentation-connect/test/integrationTest.js
- packages/zipkin-instrumentation-cujojs-rest/test/integrationTest.js
- packages/zipkin-instrumentation-fetch/test/integrationTest.js
- packages/zipkin-instrumentation-gotjs/test/integrationTest.js
- packages/zipkin-instrumentation-request-promise/test/integrationTest.js
- packages/zipkin-instrumentation-request/test/integrationTest.js
- packages/zipkin-instrumentation-superagent/test/integrationTest.js
- test/middleware.js
This is just an effort to reduce cognitive glitches.
> Changes integration tests to use more semantic status codes

- packages/zipkin-instrumentation-connect/test/integrationTest.js
- packages/zipkin-instrumentation-express/package.json
- packages/zipkin-instrumentation-express/test/expressMiddlewareIntegrationTest.js
express proxy will be a later commit.
> Rewrites express tests into v2 format

- karma.conf.js
See https://github.com/karma-runner/karma-mocha/issues/76
> Ensures when browser tests fail, we see object diffs

- packages/zipkin/src/tracer/index.js
- packages/zipkin/test/tracer.test.js
> Loosens type checking during join as it can mismatch due to transpilation

- .travis.yml
- package.json
> chore: adds lerna publish for merges.

- .travis.yml
> chore: remove builds for Node 8.
